This notebook will analzye the rate of mergers within a CE and compare that to the overall event rate for systems that merge due to GW in a hubble time.

In order to do this we will need ot rerun FCI and select for WD+WD systems that merge within CE (RLOF post CE)

In [11]:
#importing, make sure the kernel is correct or the module will be unknown
import h5py as h5
import pandas as pd
from astropy.table import Table
from astropy import units as u
from astropy import constants as const
import numpy as np
import matplotlib.pyplot as plt
plt.rc('text.latex', preamble=r'\usepackage{textgreek}')

In [12]:
import sys
import os

# Add the subdir to sys.path
sys.path.append('/home/jovyan/home/research_work/useful_py_scripts/')

# Now you can import the module
import useful_fncs

In [13]:
# reading in the HDF5 file - this file is the AIS file that we should expect many WDs in
pathToWDWD_edit_H5 = '/home/jovyan/home/copy_h5_files/COMPAS_Output_wWeights.h5' #path of the hdf5 file
Data_WD_edit = h5.File(pathToWDWD_edit_H5)

In [14]:
# we want to read in the bse_system_paramtetrs to get information about thes different systems
DCO_OG = pd.DataFrame() # making a pandas dataframe
for key in Data_WD_edit["BSE_Double_Compact_Objects"].keys(): #looping through the \"keys\" or paramters in BSE_System_Parameters
    DCO_OG[key] = Data_WD_edit["BSE_Double_Compact_Objects"][key][()] # adding these columns to the dataframe"

Let's drop any columns we don't think are necessary to have anymore

In [15]:
DCO_OG = DCO_OG.drop(['dmMT(1)','dmMT(2)','dmWinds(1)','dmWinds(2)'],axis=1)

In [16]:
DCO_OG

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,Recycled_NS(1),Recycled_NS(2),SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight
0,0,2.328412e+13,1.110223e-16,0,b'4 ',b'NA ',31.911977,27.289501,0,0.000473,0,1,0,0,158,43.919694,14,14,4.347694,10.000000
1,0,3.974767e+19,5.431362e-02,0,b'NA ',b'NA ',5.843895,5.255385,0,0.000179,0,1,0,0,326,453.863126,14,14,16.329921,10.000000
2,1,6.281330e+02,5.821410e-01,0,b'2 ',b'4-8 ',9.648989,1.454633,1,0.001588,0,1,0,0,695,0.033701,14,13,14.260153,10.000000
3,1,5.402979e+03,9.111420e-01,0,b'4 ',b'5-8 ',3.382412,1.470501,1,0.000260,0,1,0,0,858,0.114685,14,13,19.579543,10.000000
4,0,8.206604e+18,6.933256e-01,0,b'NA ',b'NA ',10.933214,2.614135,0,0.001677,0,1,0,0,948,557.934571,14,14,31.652154,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,1,1.977954e+05,5.422785e-01,0,b'2-9 ',b'5-8 ',1.260006,1.204723,0,0.014732,0,1,1,0,749623,0.052772,13,13,52.212536,0.325322
459,1,7.462776e+03,8.100584e-01,0,b'2 ',b'5 ',1.260000,1.665170,1,0.001125,0,1,0,0,769721,0.048950,13,13,45.239838,8.307509
460,1,1.917641e+02,3.043255e-01,0,b'2 ',b'4-8 ',1.260154,1.136818,1,0.000217,0,1,1,0,818419,0.007318,13,13,52.136253,1.178239
461,1,8.549317e+04,4.002102e-01,0,b'2 ',b'5-8 ',1.260015,1.203535,0,0.000424,0,1,1,0,934784,0.036748,13,13,44.343411,2.480558
462,1,4.473679e+03,9.167880e-01,0,b'2 ',b'5-8 ',1.260003,1.162398,1,0.000810,0,1,1,0,975521,0.071350,13,13,50.761040,0.671464

Now that we see what columns are needed for BSE_DCOs let's look at BSE_System_Parameters to look at what information we already have

In [17]:
# we want to read in the bse_system_paramtetrs to get information about thes different systems
WD_SP_edit = pd.DataFrame() # making a pandas dataframe

for key in Data_WD_edit["BSE_System_Parameters"].keys(): #looping through the "keys" or paramters in BSE_System_Parameters
    WD_SP_edit[key] = Data_WD_edit["BSE_System_Parameters"][key][()] # adding these columns to the dataframe

In [18]:
WD_SP_edit = WD_SP_edit.drop(['Applied_Kick_Magnitude(1)','Applied_Kick_Magnitude(2)','CE_Alpha','CH_on_MS(1)', \
'CH_on_MS(2)','Drawn_Kick_Magnitude(1)','Drawn_Kick_Magnitude(2)','Equilibrated_At_Birth','Error','Evolution_Status',\
'Eccentricity@ZAMS','LBV_Factor','Mass@ZAMS(1)','Mass@ZAMS(2)','Merger_At_Birth','Metallicity@ZAMS(2)','Omega@ZAMS(1)','Omega@ZAMS(2)',\
'SN_Kick_Magnitude_Random_Number(1)','SN_Kick_Magnitude_Random_Number(2)','SN_Kick_Mean_Anomaly(1)','SN_Kick_Mean_Anomaly(2)', \
'SN_Kick_Phi(1)','SN_Kick_Phi(2)','SN_Kick_Theta(1)','SN_Kick_Theta(2)','SemiMajorAxis@ZAMS','Sigma_Kick_CCSN_BH','Sigma_Kick_CCSN_NS','Sigma_Kick_ECSN','Sigma_Kick_USSN','Stellar_Type@ZAMS(1)','Stellar_Type@ZAMS(2)','SystemicSpeed','Unbound','WR_Factor'],axis=1)

Let's select for systems that RLOF post CE - this means that they are still interacting after their CE has ejected - potential merger within the CE

In [19]:
# selecting for when the RLOF post CE flag is set to true
rlof_post_ce = WD_SP_edit['Immediate_RLOF>CE']==True
print(sum(rlof_post_ce))
WD_SP_edit_CE = WD_SP_edit[rlof_post_ce]

60254

Let's make sure the systems we select are not alost experiencing a stellar merger

In [23]:
stellar_merger_false = WD_SP_edit_CE['Merger']==False
print(sum(stellar_merger_false))
WD_SP_edit_GW = WD_SP_edit_CE[stellar_merger_false]
WD_SP_edit_GW

0

Empty DataFrame
Columns: [CE_Event_Counter, Eccentricity, Immediate_RLOF>CE, MT_Donor_Hist(1), MT_Donor_Hist(2), Mass(1), Mass(2), Merger, Metallicity@ZAMS(1), Optimistic_CE, Record_Type, SEED, SemiMajorAxis, Stellar_Type(1), Stellar_Type(2), Time, mixture_weight]
Index: []

There re no places where stellar merger is marked true, so these systems are thought to be undergoing a stellar merger because they are in rlof post ce? If these systems are truly the mergers within a CE, then let's find the coaslescence time for these systems.

#### Let's calculate the coalescence time and merges hubble time columns

Before doing this though we need to make sure we are only calculating these parameters for WD+WD

In [26]:
# let's now create a dataframe where the above criteria is met based on all of the bools

# WDWD_EDIT_SYS = WD_SP_edit_GW.loc[(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[0])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[1])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[2])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[3])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[4])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[5])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[6])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[7])|(useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_GW)[8])]
# WDWD_EDIT_SYS
# still selecting for COWD because these are what cause the thermonuclear explosions
HeWD_bool,COWD_bool,ONeWD_bool,HeCOWD_bool,HeONeWD_bool,COHeWD_bool,COONeWD_bool,ONeHeWD_bool,ONeCOWD_bool = useful_fncs.WD_BINARY_BOOLS(WD_SP_edit_CE)
carbon_oxygen_bool = np.logical_or(ONeCOWD_bool,np.logical_or(COONeWD_bool,np.logical_or(COHeWD_bool,np.logical_or(COWD_bool,HeCOWD_bool))))
WDWD_EDIT_SYS = WD_SP_edit_CE[carbon_oxygen_bool]
WDWD_EDIT_SYS

,CE_Event_Counter,Eccentricity,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merger,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,SEED,SemiMajorAxis,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight
79,2,0.0,1,b'5 ',b'3 ',0.629323,0.227306,1,0.000261,0,1,79,0.050954,11,10,3502.246069,8.902695
721,1,0.0,1,b'2 ',b'3 ',0.427625,0.266958,1,0.000173,0,1,721,0.044531,11,10,2897.537318,9.999995
995,1,0.0,1,b'2 ',b'3 ',0.500912,0.254681,1,0.000220,0,1,995,0.048608,11,10,2977.884633,9.999843
1920,2,0.0,1,b'5 ',b'3 ',0.628376,0.230575,1,0.000426,0,1,1920,0.043623,11,10,2586.847128,4.015607
2262,2,0.0,1,b'5 ',b'3 ',0.615465,0.210094,1,0.001030,0,1,2262,0.037937,11,10,3237.663898,8.718167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,0.0,1,b'5 ',b'3 ',0.620606,0.271493,1,0.001361,0,1,941708,0.053502,11,10,2216.722739,6.121413
952257,2,0.0,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,0,1,952257,0.035513,11,10,4112.829807,3.979722
993759,2,0.0,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,0,1,993759,0.059460,11,10,8726.570289,5.455787
997177,2,0.0,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,0,1,997177,0.035409,11,10,2816.643085,2.332583
999213,2,0.0,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,0,1,999213,0.053816,11,10,4968.076814,3.812886

In [27]:
print(np.unique(WDWD_EDIT_SYS['Stellar_Type(1)']))
print(np.unique(WDWD_EDIT_SYS['Stellar_Type(2)']))

[11]
[10]

In the equation for coalescence time, M1 refers to the more massive star whereas M2 refers to the less massive one. I need to make new columns (witht eh help of Lieke) to find these more massive and less massive stars in each bianry. Let's do a check to see if our colaescence times match the COMPAS calculations

In [ ]:
# unit_dict = {b'Rsol':u.Rsun,
#              b'AU':u.AU}

# print(unit_dict[b'AU'])

In [28]:
# let's first look at the units of some parameters to see if anything must be converted
SPs_WD = Data_WD_edit['BSE_System_Parameters']
print(SPs_WD['Mass(1)'].attrs['units']) 
print(SPs_WD['SemiMajorAxis'].attrs['units'])
print(SPs_WD['Time'].attrs['units'])

b'Msol'
b'Rsol'
b'Myr'

In [29]:
# let's first look at the units of some parameters to see if anything must be converted
dcos_WD = Data_WD_edit['BSE_Double_Compact_Objects']
print(dcos_WD['Mass(1)'].attrs['units']) 
print(dcos_WD['SemiMajorAxis@DCO'].attrs['units'])
print(dcos_WD['Time'].attrs['units'])

b'Msol'
b'AU'
b'Myr'

#### Let's now calculated the coalescence time to our table of WD+WD

In [30]:
# Add columns for the more and less massive compact object

WDWD_EDIT_SYS['M_moremass'] = WDWD_EDIT_SYS[['Mass(1)', 'Mass(2)']].max(axis=1)
WDWD_EDIT_SYS['M_lessmass'] = WDWD_EDIT_SYS[['Mass(1)', 'Mass(2)']].min(axis=1)

/tmp/ipykernel_57300/3822573989.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WDWD_EDIT_SYS['M_moremass'] = WDWD_EDIT_SYS[['Mass(1)', 'Mass(2)']].max(axis=1)
/tmp/ipykernel_57300/3822573989.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WDWD_EDIT_SYS['M_lessmass'] = WDWD_EDIT_SYS[['Mass(1)', 'Mass(2)']].min(axis=1)

In [31]:
time_col_wd = useful_fncs.tgw((WDWD_EDIT_SYS['SemiMajorAxis'].values),(WDWD_EDIT_SYS['Eccentricity']),(WDWD_EDIT_SYS['M_moremass'].values),(WDWD_EDIT_SYS['M_lessmass'].values),Data_WD_edit,'BSE_System_Parameters','SemiMajorAxis')

In [32]:
# let's insert the check if there was a merger before hubble time into our dataframe

# only run this cell once per table creation
WDWD_EDIT_SYS.insert(1,"Coalescence_Time",time_col_wd,True)
WDWD_EDIT_SYS

,CE_Event_Counter,Coalescence_Time,Eccentricity,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merger,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,SEED,SemiMajorAxis,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight,M_moremass,M_lessmass
79,2,0.008269,0.0,1,b'5 ',b'3 ',0.629323,0.227306,1,0.000261,0,1,79,0.050954,11,10,3502.246069,8.902695,0.629323,0.227306
721,1,0.007454,0.0,1,b'2 ',b'3 ',0.427625,0.266958,1,0.000173,0,1,721,0.044531,11,10,2897.537318,9.999995,0.427625,0.266958
995,1,0.008705,0.0,1,b'2 ',b'3 ',0.500912,0.254681,1,0.000220,0,1,995,0.048608,11,10,2977.884633,9.999843,0.500912,0.254681
1920,2,0.004374,0.0,1,b'5 ',b'3 ',0.628376,0.230575,1,0.000426,0,1,1920,0.043623,11,10,2586.847128,4.015607,0.628376,0.230575
2262,2,0.002917,0.0,1,b'5 ',b'3 ',0.615465,0.210094,1,0.001030,0,1,2262,0.037937,11,10,3237.663898,8.718167,0.615465,0.210094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,0.008193,0.0,1,b'5 ',b'3 ',0.620606,0.271493,1,0.001361,0,1,941708,0.053502,11,10,2216.722739,6.121413,0.620606,0.271493
952257,2,0.002799,0.0,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,0,1,952257,0.035513,11,10,4112.829807,3.979722,0.560866,0.200119
993759,2,0.021053,0.0,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,0,1,993759,0.059460,11,10,8726.570289,5.455787,0.555536,0.209873
997177,2,0.003581,0.0,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,0,1,997177,0.035409,11,10,2816.643085,2.332583,0.411248,0.244632
999213,2,0.011354,0.0,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,0,1,999213,0.053816,11,10,4968.076814,3.812886,0.621104,0.214069

In [ ]:
# in case you run the cell above more than once here is a way to remove the extra column
# WDWD_EDIT_SYS = WDWD_EDIT_SYS.drop('Coalescence_Time', axis=1)

We now need to calcualte the delay time to then see if this time is within a hubble time

In [33]:
# let's convert the columns of the data frame into numpy arrays to be able to do operations with them
time = np.array(WDWD_EDIT_SYS['Time'])
t_col = np.array(WDWD_EDIT_SYS['Coalescence_Time'])

t_delay = [] # this will hold the delay time in Myr

for binaries in range(WDWD_EDIT_SYS.shape[0]):

    delay = time[binaries] + t_col[binaries] # adding the two values together to get the delay time
    t_delay.append(delay)

In [34]:
# first let's take the delay time column and make it a numpy array
delay_time = np.array(t_delay)

# the age of the universe
age_universe = (13.7e9)*(1e-6) # converting from yr to Myr

hubble_merger = []

for times in delay_time:

    if (times > age_universe):
        hubble_merger.append(0)

    elif (times < age_universe):
        hubble_merger.append(1)

In [35]:
# let's insert the check if there was a merger before hubble time into our dataframe

# only run this cell once per table creation
WDWD_EDIT_SYS.insert(8,"Merges_Hubble_Time",hubble_merger,True)

In [ ]:
# in case you need to remove the column
# WDWD_SYS = WDWD_SYS.drop('Merges_Hubble_Time', axis=1)

In [36]:
WDWD_EDIT_SYS

,CE_Event_Counter,Coalescence_Time,Eccentricity,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Merger,...,Optimistic_CE,Record_Type,SEED,SemiMajorAxis,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight,M_moremass,M_lessmass
79,2,0.008269,0.0,1,b'5 ',b'3 ',0.629323,0.227306,1,1,...,0,1,79,0.050954,11,10,3502.246069,8.902695,0.629323,0.227306
721,1,0.007454,0.0,1,b'2 ',b'3 ',0.427625,0.266958,1,1,...,0,1,721,0.044531,11,10,2897.537318,9.999995,0.427625,0.266958
995,1,0.008705,0.0,1,b'2 ',b'3 ',0.500912,0.254681,1,1,...,0,1,995,0.048608,11,10,2977.884633,9.999843,0.500912,0.254681
1920,2,0.004374,0.0,1,b'5 ',b'3 ',0.628376,0.230575,1,1,...,0,1,1920,0.043623,11,10,2586.847128,4.015607,0.628376,0.230575
2262,2,0.002917,0.0,1,b'5 ',b'3 ',0.615465,0.210094,1,1,...,0,1,2262,0.037937,11,10,3237.663898,8.718167,0.615465,0.210094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,0.008193,0.0,1,b'5 ',b'3 ',0.620606,0.271493,1,1,...,0,1,941708,0.053502,11,10,2216.722739,6.121413,0.620606,0.271493
952257,2,0.002799,0.0,1,b'5 ',b'3 ',0.560866,0.200119,1,1,...,0,1,952257,0.035513,11,10,4112.829807,3.979722,0.560866,0.200119
993759,2,0.021053,0.0,1,b'5 ',b'3 ',0.555536,0.209873,1,1,...,0,1,993759,0.059460,11,10,8726.570289,5.455787,0.555536,0.209873
997177,2,0.003581,0.0,1,b'4 ',b'3 ',0.411248,0.244632,1,1,...,0,1,997177,0.035409,11,10,2816.643085,2.332583,0.411248,0.244632
999213,2,0.011354,0.0,1,b'5 ',b'3 ',0.621104,0.214069,1,1,...,0,1,999213,0.053816,11,10,4968.076814,3.812886,0.621104,0.214069

Let's look at where the \"Merges_Hubble_Time\" is set to true

In [37]:
# there is only one system that merges before hubble time
WDWD_Merge = WDWD_EDIT_SYS[WDWD_EDIT_SYS['Merges_Hubble_Time']==True]
WDWD_Merge

,CE_Event_Counter,Coalescence_Time,Eccentricity,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Merger,...,Optimistic_CE,Record_Type,SEED,SemiMajorAxis,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight,M_moremass,M_lessmass
79,2,0.008269,0.0,1,b'5 ',b'3 ',0.629323,0.227306,1,1,...,0,1,79,0.050954,11,10,3502.246069,8.902695,0.629323,0.227306
721,1,0.007454,0.0,1,b'2 ',b'3 ',0.427625,0.266958,1,1,...,0,1,721,0.044531,11,10,2897.537318,9.999995,0.427625,0.266958
995,1,0.008705,0.0,1,b'2 ',b'3 ',0.500912,0.254681,1,1,...,0,1,995,0.048608,11,10,2977.884633,9.999843,0.500912,0.254681
1920,2,0.004374,0.0,1,b'5 ',b'3 ',0.628376,0.230575,1,1,...,0,1,1920,0.043623,11,10,2586.847128,4.015607,0.628376,0.230575
2262,2,0.002917,0.0,1,b'5 ',b'3 ',0.615465,0.210094,1,1,...,0,1,2262,0.037937,11,10,3237.663898,8.718167,0.615465,0.210094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,0.008193,0.0,1,b'5 ',b'3 ',0.620606,0.271493,1,1,...,0,1,941708,0.053502,11,10,2216.722739,6.121413,0.620606,0.271493
952257,2,0.002799,0.0,1,b'5 ',b'3 ',0.560866,0.200119,1,1,...,0,1,952257,0.035513,11,10,4112.829807,3.979722,0.560866,0.200119
993759,2,0.021053,0.0,1,b'5 ',b'3 ',0.555536,0.209873,1,1,...,0,1,993759,0.059460,11,10,8726.570289,5.455787,0.555536,0.209873
997177,2,0.003581,0.0,1,b'4 ',b'3 ',0.411248,0.244632,1,1,...,0,1,997177,0.035409,11,10,2816.643085,2.332583,0.411248,0.244632
999213,2,0.011354,0.0,1,b'5 ',b'3 ',0.621104,0.214069,1,1,...,0,1,999213,0.053816,11,10,4968.076814,3.812886,0.621104,0.214069

In [38]:
# making sure all of these systems do not experience a stellar merger
bool_merge = WDWD_Merge['Merger']==False
sum(bool_merge)

0

In [39]:
# let's drop the merger column but make a note that all of these systems are considered stellar mergers
WDWD_Merge = WDWD_Merge.drop('Merger', axis=1)

#### Let's add our WD+WD that merged within a hubble time to the hdf5 file

Before concatenating the WD+WD to the original DCO table we need to rename some of the columns in our WD table so that they match up with the DCO table

In [40]:
WDWD_Merge = WDWD_Merge.rename(columns={'Eccentricity':'Eccentricity@DCO','SemiMajorAxis':'SemiMajorAxis@DCO'})

In [41]:
WDWD_Merge

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight,M_moremass,M_lessmass
79,2,0.008269,0.0,1,b'5 ',b'3 ',0.629323,0.227306,1,0.000261,0,1,79,0.050954,11,10,3502.246069,8.902695,0.629323,0.227306
721,1,0.007454,0.0,1,b'2 ',b'3 ',0.427625,0.266958,1,0.000173,0,1,721,0.044531,11,10,2897.537318,9.999995,0.427625,0.266958
995,1,0.008705,0.0,1,b'2 ',b'3 ',0.500912,0.254681,1,0.000220,0,1,995,0.048608,11,10,2977.884633,9.999843,0.500912,0.254681
1920,2,0.004374,0.0,1,b'5 ',b'3 ',0.628376,0.230575,1,0.000426,0,1,1920,0.043623,11,10,2586.847128,4.015607,0.628376,0.230575
2262,2,0.002917,0.0,1,b'5 ',b'3 ',0.615465,0.210094,1,0.001030,0,1,2262,0.037937,11,10,3237.663898,8.718167,0.615465,0.210094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,0.008193,0.0,1,b'5 ',b'3 ',0.620606,0.271493,1,0.001361,0,1,941708,0.053502,11,10,2216.722739,6.121413,0.620606,0.271493
952257,2,0.002799,0.0,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,0,1,952257,0.035513,11,10,4112.829807,3.979722,0.560866,0.200119
993759,2,0.021053,0.0,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,0,1,993759,0.059460,11,10,8726.570289,5.455787,0.555536,0.209873
997177,2,0.003581,0.0,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,0,1,997177,0.035409,11,10,2816.643085,2.332583,0.411248,0.244632
999213,2,0.011354,0.0,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,0,1,999213,0.053816,11,10,4968.076814,3.812886,0.621104,0.214069

In [42]:
#let's now match up the tables
DCO_appended_table = pd.concat([DCO_OG,WDWD_Merge])

In [43]:
DCO_appended_table

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),...,Recycled_NS(1),Recycled_NS(2),SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight,M_moremass,M_lessmass
0,0,2.328412e+13,1.110223e-16,0,b'4 ',b'NA ',31.911977,27.289501,0,0.000473,...,0.0,0.0,158,43.919694,14,14,4.347694,10.000000,NaN,NaN
1,0,3.974767e+19,5.431362e-02,0,b'NA ',b'NA ',5.843895,5.255385,0,0.000179,...,0.0,0.0,326,453.863126,14,14,16.329921,10.000000,NaN,NaN
2,1,6.281330e+02,5.821410e-01,0,b'2 ',b'4-8 ',9.648989,1.454633,1,0.001588,...,0.0,0.0,695,0.033701,14,13,14.260153,10.000000,NaN,NaN
3,1,5.402979e+03,9.111420e-01,0,b'4 ',b'5-8 ',3.382412,1.470501,1,0.000260,...,0.0,0.0,858,0.114685,14,13,19.579543,10.000000,NaN,NaN
4,0,8.206604e+18,6.933256e-01,0,b'NA ',b'NA ',10.933214,2.614135,0,0.001677,...,0.0,0.0,948,557.934571,14,14,31.652154,10.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,8.193485e-03,0.000000e+00,1,b'5 ',b'3 ',0.620606,0.271493,1,0.001361,...,NaN,NaN,941708,0.053502,11,10,2216.722739,6.121413,0.620606,0.271493
952257,2,2.798890e-03,0.000000e+00,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,...,NaN,NaN,952257,0.035513,11,10,4112.829807,3.979722,0.560866,0.200119
993759,2,2.105304e-02,0.000000e+00,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,...,NaN,NaN,993759,0.059460,11,10,8726.570289,5.455787,0.555536,0.209873
997177,2,3.580759e-03,0.000000e+00,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,...,NaN,NaN,997177,0.035409,11,10,2816.643085,2.332583,0.411248,0.244632
999213,2,1.135378e-02,0.000000e+00,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,...,NaN,NaN,999213,0.053816,11,10,4968.076814,3.812886,0.621104,0.214069

In [44]:
# let's drop the extra 
DCO_appended_table = DCO_appended_table.drop('M_moremass', axis=1)
DCO_appended_table = DCO_appended_table.drop('M_lessmass', axis=1)

In [45]:
DCO_appended_table

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,Recycled_NS(1),Recycled_NS(2),SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight
0,0,2.328412e+13,1.110223e-16,0,b'4 ',b'NA ',31.911977,27.289501,0,0.000473,0,1,0.0,0.0,158,43.919694,14,14,4.347694,10.000000
1,0,3.974767e+19,5.431362e-02,0,b'NA ',b'NA ',5.843895,5.255385,0,0.000179,0,1,0.0,0.0,326,453.863126,14,14,16.329921,10.000000
2,1,6.281330e+02,5.821410e-01,0,b'2 ',b'4-8 ',9.648989,1.454633,1,0.001588,0,1,0.0,0.0,695,0.033701,14,13,14.260153,10.000000
3,1,5.402979e+03,9.111420e-01,0,b'4 ',b'5-8 ',3.382412,1.470501,1,0.000260,0,1,0.0,0.0,858,0.114685,14,13,19.579543,10.000000
4,0,8.206604e+18,6.933256e-01,0,b'NA ',b'NA ',10.933214,2.614135,0,0.001677,0,1,0.0,0.0,948,557.934571,14,14,31.652154,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941708,2,8.193485e-03,0.000000e+00,1,b'5 ',b'3 ',0.620606,0.271493,1,0.001361,0,1,NaN,NaN,941708,0.053502,11,10,2216.722739,6.121413
952257,2,2.798890e-03,0.000000e+00,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,0,1,NaN,NaN,952257,0.035513,11,10,4112.829807,3.979722
993759,2,2.105304e-02,0.000000e+00,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,0,1,NaN,NaN,993759,0.059460,11,10,8726.570289,5.455787
997177,2,3.580759e-03,0.000000e+00,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,0,1,NaN,NaN,997177,0.035409,11,10,2816.643085,2.332583
999213,2,1.135378e-02,0.000000e+00,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,0,1,NaN,NaN,999213,0.053816,11,10,4968.076814,3.812886

In [46]:
DCO_appended_table.sort_values(by="SEED")

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,Recycled_NS(1),Recycled_NS(2),SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight
79,2,8.268605e-03,0.000000e+00,1,b'5 ',b'3 ',0.629323,0.227306,1,0.000261,0,1,NaN,NaN,79,0.050954,11,10,3502.246069,8.902695
0,0,2.328412e+13,1.110223e-16,0,b'4 ',b'NA ',31.911977,27.289501,0,0.000473,0,1,0.0,0.0,158,43.919694,14,14,4.347694,10.000000
1,0,3.974767e+19,5.431362e-02,0,b'NA ',b'NA ',5.843895,5.255385,0,0.000179,0,1,0.0,0.0,326,453.863126,14,14,16.329921,10.000000
2,1,6.281330e+02,5.821410e-01,0,b'2 ',b'4-8 ',9.648989,1.454633,1,0.001588,0,1,0.0,0.0,695,0.033701,14,13,14.260153,10.000000
721,1,7.454232e-03,0.000000e+00,1,b'2 ',b'3 ',0.427625,0.266958,1,0.000173,0,1,NaN,NaN,721,0.044531,11,10,2897.537318,9.999995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952257,2,2.798890e-03,0.000000e+00,1,b'5 ',b'3 ',0.560866,0.200119,1,0.003040,0,1,NaN,NaN,952257,0.035513,11,10,4112.829807,3.979722
462,1,4.473679e+03,9.167880e-01,0,b'2 ',b'5-8 ',1.260003,1.162398,1,0.000810,0,1,1.0,0.0,975521,0.071350,13,13,50.761040,0.671464
993759,2,2.105304e-02,0.000000e+00,1,b'5 ',b'3 ',0.555536,0.209873,1,0.004706,0,1,NaN,NaN,993759,0.059460,11,10,8726.570289,5.455787
997177,2,3.580759e-03,0.000000e+00,1,b'4 ',b'3 ',0.411248,0.244632,1,0.002037,0,1,NaN,NaN,997177,0.035409,11,10,2816.643085,2.332583
999213,2,1.135378e-02,0.000000e+00,1,b'5 ',b'3 ',0.621104,0.214069,1,0.000369,0,1,NaN,NaN,999213,0.053816,11,10,4968.076814,3.812886

In [47]:
# let's save this table as a csv so we can add it to the edited hdf5 file

DCO_appended_table.to_csv('DCO_RLOF_POST_CE.csv',index=False)

In [48]:
Data_WD_edit.close()

### Let's now rewrite the hdf5 file so that we can run FastCosmicIntegration on it

In [49]:
# let's create a group that we wil called BSE_DCOs using out csv file

# Example CSV file path
csv_file = 'DCO_RLOF_POST_CE.csv'

# Open or create an HDF5 file
with h5.File(pathToWDWD_edit_H5, 'a') as hdf_file:
    
    # deleting the previous DCO group
    del hdf_file['BSE_Double_Compact_Objects']
    print('Original BSE_Double_Compact_Objects Group deleted.')

    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv(csv_file)
    
    # Create a group (if not already created)
    group_name = 'BSE_Double_Compact_Objects'
    if group_name not in hdf_file:
        group = hdf_file.create_group(group_name)
    else:
        group = hdf_file[group_name]

   # Create datasets for each column in the CSV file
    for column in df.columns:
        dataset_name = column


        # Handle existing dataset
        if dataset_name in group:

            # Option 1: Overwrite existing dataset
            del group[dataset_name]
            dataset = group.create_dataset(dataset_name,data=df[column].to_numpy())

            # Option 2: Rename existing dataset
            # new_dataset_name = f"{dataset_name}_new"
            # dataset = group.create_dataset(new_dataset_name, data=df[column].to_numpy())

        else:
            # Create dataset and write data from DataFrame
            dataset = group.create_dataset(dataset_name, data=df[column].to_numpy())
            
            # Optionally, add attributes to the dataset (if needed)
            dataset.attrs['description'] = f'Data for column {column} from CSV file'
    
print(f'CSV data from {csv_file} added to group "{group_name}" in HDF5 file: {pathToWDWD_edit_H5}')

Original BSE_Double_Compact_Objects Group deleted.
CSV data from DCO_RLOF_POST_CE.csv added to group "BSE_Double_Compact_Objects" in HDF5 file: /home/jovyan/home/copy_h5_files/COMPAS_Output_wWeights.h5

In [50]:
# reading in the HDF5 file - this file is the AIS file that we should expect many WDs in
pathToWDWD_edit_H5 = '/home/jovyan/home/edit_hdf5/WDWD/v02.46.01/COMPAS_Output_wWeights_CE.h5' #path of the hdf5 file
Data_WD_edit = h5.File(pathToWDWD_edit_H5)

Let's check if this new group has been added to the hdf5 file

In [51]:
Data_WD_edit.keys()

Let's now check to see if the correct dataset names are present

In [52]:
DCOWDs = Data_WD_edit['BSE_Double_Compact_Objects'] #specifically looking at the supernovae events
list(DCOWDs.keys()) #listing the parameters recorded for each supernova

['CE_Event_Counter',
 'Coalescence_Time',
 'Eccentricity@DCO',
 'Immediate_RLOF>CE',
 'MT_Donor_Hist(1)',
 'MT_Donor_Hist(2)',
 'Mass(1)',
 'Mass(2)',
 'Merges_Hubble_Time',
 'Metallicity@ZAMS(1)',
 'Optimistic_CE',
 'Record_Type',
 'Recycled_NS(1)',
 'Recycled_NS(2)',
 'SEED',
 'SemiMajorAxis@DCO',
 'Stellar_Type(1)',
 'Stellar_Type(2)',
 'Time',
 'mixture_weight']

In [53]:
# let's open this group 
# we want to read in the bse_system_paramtetrs to get information about thes different systems
DCO_WD = pd.DataFrame() # making a pandas dataframe
for key in Data_WD_edit["BSE_Double_Compact_Objects"].keys(): #looping through the \"keys\" or paramters in BSE_System_Parameters
    DCO_WD[key] = Data_WD_edit["BSE_Double_Compact_Objects"][key][()] # adding these columns to the dataframe"

In [54]:
DCO_WD

,CE_Event_Counter,Coalescence_Time,Eccentricity@DCO,Immediate_RLOF>CE,MT_Donor_Hist(1),MT_Donor_Hist(2),Mass(1),Mass(2),Merges_Hubble_Time,Metallicity@ZAMS(1),Optimistic_CE,Record_Type,Recycled_NS(1),Recycled_NS(2),SEED,SemiMajorAxis@DCO,Stellar_Type(1),Stellar_Type(2),Time,mixture_weight
0,0,2.328412e+13,1.110223e-16,0,"b""b'4 '""","b""b'NA '""",31.911977,27.289501,0,0.000473,0,1,0.0,0.0,158,43.919694,14,14,4.347694,10.000000
1,0,3.974767e+19,5.431362e-02,0,"b""b'NA '""","b""b'NA '""",5.843895,5.255385,0,0.000179,0,1,0.0,0.0,326,453.863126,14,14,16.329921,10.000000
2,1,6.281330e+02,5.821410e-01,0,"b""b'2 '""","b""b'4-8 '""",9.648989,1.454633,1,0.001588,0,1,0.0,0.0,695,0.033701,14,13,14.260153,10.000000
3,1,5.402979e+03,9.111420e-01,0,"b""b'4 '""","b""b'5-8 '""",3.382412,1.470501,1,0.000260,0,1,0.0,0.0,858,0.114685,14,13,19.579543,10.000000
4,0,8.206604e+18,6.933256e-01,0,"b""b'NA '""","b""b'NA '""",10.933214,2.614135,0,0.001677,0,1,0.0,0.0,948,557.934571,14,14,31.652154,10.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
807,2,8.193485e-03,0.000000e+00,1,"b""b'5 '""","b""b'3 '""",0.620606,0.271493,1,0.001361,0,1,NaN,NaN,941708,0.053502,11,10,2216.722739,6.121413
808,2,2.798890e-03,0.000000e+00,1,"b""b'5 '""","b""b'3 '""",0.560866,0.200119,1,0.003040,0,1,NaN,NaN,952257,0.035513,11,10,4112.829807,3.979722
809,2,2.105304e-02,0.000000e+00,1,"b""b'5 '""","b""b'3 '""",0.555536,0.209873,1,0.004706,0,1,NaN,NaN,993759,0.059460,11,10,8726.570289,5.455787
810,2,3.580759e-03,0.000000e+00,1,"b""b'4 '""","b""b'3 '""",0.411248,0.244632,1,0.002037,0,1,NaN,NaN,997177,0.035409,11,10,2816.643085,2.332583
811,2,1.135378e-02,0.000000e+00,1,"b""b'5 '""","b""b'3 '""",0.621104,0.214069,1,0.000369,0,1,NaN,NaN,999213,0.053816,11,10,4968.076814,3.812886